---
title: "Food Consulting"
author: "Cooper Riggs & Stockton Nelson"
format: pdf
editor: visual
---

## Setup

```{r}
#Downloading Libraries
library(tidyverse)

#Bringing in Data
food <- vroom::vroom("FoodExpenses.txt") |>
  janitor::clean_names() |>
  rename(eating = eating_out)
```

## Problem 2 (Cooper)

### Relationship Between Income and Food Expenditures

```{r}

```

### Healthy Economy

```{r}

```

### Predictions

```{r}

```

## Problem 3 (Stockton)

### Problems with Standard Regression

```{r}
#Making Linear Model
eqlm <- lm(eating ~ ., data = food)

#Making Scatterplot of Birth Weight and Mother's Age 
ggplot(data = food, mapping = aes(x = income, y = eating)) +
  geom_point() +
  geom_smooth(method = lm, se = F) +
  labs(x = "Income in Thousands ($)",
       y = "Eating Out ($)",
       title = "Scatterplot")

#Making an Added Variable Plot
car::avPlot(eqlm, "income",
            main = "Added-Variable Plot for Income")
```

### Validate Unequal Variance Model

```{r}

```
